version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: StoreVisitTracking.API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Port=3306;Database=storevisittrackingdb;User=root;Password=root;AllowPublicKeyRetrieval=true;Pooling=true;MinimumPoolSize=10;MaximumPoolSize=200;ConnectionTimeout=120;TreatTinyAsBoolean=true;ConvertZeroDateTime=true;SslMode=Preferred;
      - Redis__Configuration=localhost:6379,abortConnect=false
      - Redis__InstanceName=StoreVisitTracking_
    networks:
      - storevisittracking-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

networks:
  storevisittracking-network:
    driver: bridge
    attachable: true

volumes:
  redis_data:
    driver: local